### ISSUE TITLE
Make Hero Section More manageable and readable

### ISSUE THREAD

**Issue by ArjunQBTech** [ICP-hub/StarDustAdventures#2]
### Tasks
- [ ] Make the code more readable and manageable by breaking down components based on their purpose.
- [ ] Rename CSS classes to be more developer-friendly (if possible)
- [ ] The UI should remain unchanged as well as the loading time

**Comment by ArjunQBTech** [comment]
@MohitQuadB complete this task by today

**Comment by MohitQuadB** [comment]
![image](https://github.com/user-attachments/assets/765dd18d-4a30-4711-9eba-3b817f8eadfc)
  This issue has been resolved by creating the jsx file for each part like content,animation ,background section etc ..have a look @ArjunQBTech
