### ISSUE TITLE
Lore Section in Landing Page is not responsive

### ISSUE THREAD

**Issue by ArjunQBTech** [ICP-hub/StarDustAdventures#3]
### Tasks : 
- [ ] Make the Component Responsive as per the Figma 
- [ ] Make the code manageable and readable
- [ ] If the implementation of the animation is hard, try to build a new Mobile View Component inside the `components/landing/loreStoryline` folder.
- [ ] Use GSAP's ScrollTrigger for animating the Component.
- [ ] Inspect the DEV Tools to see if any issue is arriving with the component before pushing

**Comment by ArjunQBTech** [comment]
#70 Fixed it
